micronaut:
  application:
    name: base
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
vertx:
  pg:
    client:
      port: 5432
      host: the-host
      database: the-db
      user: user
      password: password
      maxSize: 5
